# general
seed: 42
workers: 0
dataset_dir: "./datasets"

#dataset options
input_size: 280
class_num: 2

# train options
batch_size: 512
start_epoch: 0
epochs: 2
dataset: "BlogFeedback" # MNIST, TUANDROMD, BlogFeedback
masking_ratio: 0.2

# model options
backbone: "backbone" # backbone18 / backbone34 / backbone50
feature_dim: 256
model_path: "save/MNIST"
reload: False

# loss options
learning_rate: 0.0001
weight_decay: 0.
instance_temperature: 0.5
cluster_temperature: 1.0
