# general
seed: 42
workers: 0
dataset_dir: "./datasets"
baselines: False
latent_cluster: False

#dataset options
input_size: 784 # 784, 241, 280, 30, 2000
class_num: 10 # 10, 2, 2, 2, 4

# train options
batch_size: 512
start_epoch: 0
epochs: 2
dataset: "MNIST" # MNIST, TUANDROMD, BlogFeedback, BreastCancer, reuters
masking_ratio: 0.2

# model options
backbone: "backbone" 
feature_dim: 256
model_path: "save/MNIST"
reload: False

# loss options
learning_rate: 0.0001
weight_decay: 0.
instance_temperature: 0.5
cluster_temperature: 1.0
